baseURL = 'https://barryvanveen.nl/'
languageCode = 'en-us'
title = 'A blog about web development - Barry van Veen'
description = 'The personal blog of Barry van Veen with articles on web development.'
disableKinds = ['taxonomy', 'term']
enableRobotsTXT = true
[menus]
[[menus.main]]
    name = 'Articles'
    pageRef = '/articles'
    weight = 10
[[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 20
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'monokai'
    tabWidth = 4
[imaging]
    quality = 90
    resampleFilter = 'Lanczos'
[outputs]
    home = ['html']
    section = ['html', 'rss']
    taxonomy = []
    term = []
[[redirects]]
    from = '/**'
    status = 404
    to = '/404.html'
[taxonomies]
    type = 'types'
    subject = 'subjects'
[related]
    includeNewer = true
    threshold = 50
    toLower = true
[[related.indices]]
    applyFilter = false
    cardinalityThreshold = 50
    name = 'subjects'
    pattern = ''
    toLower = true
    type = 'basic'
    weight = 80
