baseURL = 'https://barryvanveen.nl/'
languageCode = 'en-us'
title = 'A blog about web development - Barry van Veen'
description = 'The personal blog of Barry van Veen with articles on web development.'
[menus]
[[menus.main]]
    name = 'Articles'
    pageRef = '/articles'
    weight = 10
[[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 20
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'monokai'
    tabWidth = 4
[imaging]
    quality = 90
    resampleFilter = 'Lanczos'